generator:
  class: sfDoctrineGenerator
  param:
    model_class:           PreparationForm
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          preparation_form
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
        _save_and_add:
          label: Сохранить и добавить
        _save:
          label: Сохранить
        _edit:
          label: Редактировать
        _list:
          label: Назад к списку
        _delete:
          label: Удалить
        _new:
          label: Добавить
      fields:  ~
      list:
        display: [name]
      filter:
        display: [name]
      form:
        display: [name]
      edit:    ~
      new:     ~
