<?php

/**
 * BaseReports
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $among
 * @property integer $product_id
 * @property Products $Products
 * 
 * @method string   getName()       Returns the current record's "name" value
 * @method integer  getAmong()      Returns the current record's "among" value
 * @method integer  getProductId()  Returns the current record's "product_id" value
 * @method Products getProducts()   Returns the current record's "Products" value
 * @method Reports  setName()       Sets the current record's "name" value
 * @method Reports  setAmong()      Sets the current record's "among" value
 * @method Reports  setProductId()  Sets the current record's "product_id" value
 * @method Reports  setProducts()   Sets the current record's "Products" value
 * 
 * @package    chemist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReports extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reports');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('among', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Products', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}