<?php

/**
 * PreparationFormTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreparationFormTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreparationFormTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PreparationForm');
    }
}