<?php

/**
 * ProducerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProducerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProducerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Producer');
    }
}