<?php

/**
 * Products
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    chemist
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Products extends BaseProducts
{
      public function save(Doctrine_Connection $conn = null)
{
      if (!$this->getPreparationFormId())
  {
        $this->setPreparationFormId();
  }
    return parent::save($conn);
}

}
