<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/13 01:22:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=chemist',
  'username' => 'chemist',
  'password' => 'mysql',
  'name' => 'doctrine',
)),);
