<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/02/09 16:22:39
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfwebdebugpaneldoctrine' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfwidgetformdoctrinechoice' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrineformgenerator' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinecolumn' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'swift_doctrinespool' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinerecord' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinepager' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineroutecollection' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sftesterdoctrine' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrinecli' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineexception' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfvalidatordoctrineunique' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfdoctrineconnectionlistener' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedatabase' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfformdoctrine' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinedqltask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinemigratetask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedropdbtask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinebuildschematask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildtask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinedatadumptask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinedataloadtask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinebuildformstask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinebasetask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/fairdev/projects/chemist/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',

  // project
  'preparationformformfilter' => '/home/fairdev/projects/chemist/lib/filter/doctrine/PreparationFormFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/fairdev/projects/chemist/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'productsformfilter' => '/home/fairdev/projects/chemist/lib/filter/doctrine/ProductsFormFilter.class.php',
  'basepreparationformformfilter' => '/home/fairdev/projects/chemist/lib/filter/doctrine/base/BasePreparationFormFormFilter.class.php',
  'baseproductsformfilter' => '/home/fairdev/projects/chemist/lib/filter/doctrine/base/BaseProductsFormFilter.class.php',
  'baseformdoctrine' => '/home/fairdev/projects/chemist/lib/form/doctrine/BaseFormDoctrine.class.php',
  'preparationformform' => '/home/fairdev/projects/chemist/lib/form/doctrine/PreparationFormForm.class.php',
  'productsform' => '/home/fairdev/projects/chemist/lib/form/doctrine/ProductsForm.class.php',
  'baseproductsform' => '/home/fairdev/projects/chemist/lib/form/doctrine/base/BaseProductsForm.class.php',
  'basepreparationformform' => '/home/fairdev/projects/chemist/lib/form/doctrine/base/BasePreparationFormForm.class.php',
  'baseform' => '/home/fairdev/projects/chemist/lib/form/BaseForm.class.php',

  // project_model
  'products' => '/home/fairdev/projects/chemist/lib/model/doctrine/Products.class.php',
  'preparationformtable' => '/home/fairdev/projects/chemist/lib/model/doctrine/PreparationFormTable.class.php',
  'productstable' => '/home/fairdev/projects/chemist/lib/model/doctrine/ProductsTable.class.php',
  'basepreparationform' => '/home/fairdev/projects/chemist/lib/model/doctrine/base/BasePreparationForm.class.php',
  'baseproducts' => '/home/fairdev/projects/chemist/lib/model/doctrine/base/BaseProducts.class.php',
  'preparationform' => '/home/fairdev/projects/chemist/lib/model/doctrine/PreparationForm.class.php',

  // application
  'myuser' => '/home/fairdev/projects/chemist/apps/backend/lib/myUser.class.php',

  // modules
  'products/productsgeneratorhelper' => '/home/fairdev/projects/chemist/apps/backend/modules/products/lib/productsGeneratorHelper.class.php',
  'products/productsgeneratorconfiguration' => '/home/fairdev/projects/chemist/apps/backend/modules/products/lib/productsGeneratorConfiguration.class.php',
);
