<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/12 21:18:26

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=chemist',
  'username' => 'root',
  'password' => 666,
  'name' => 'doctrine',
)),);
