<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/02/12 13:38:34
sfConfig::add(array(
  'mod_preparationform_enabled' => true,
  'mod_preparationform_view_class' => 'sfPHP',
));
