<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/02/09 15:01:46
sfConfig::add(array(
  'mod_preparationform_enabled' => true,
  'mod_preparationform_view_class' => 'sfPHP',
));
