<?php
// auto-generated by sfDatabaseConfigHandler
<<<<<<< HEAD
// date: 2012/02/12 12:47:42
=======
// date: 2012/02/12 17:19:17
>>>>>>> b4f031de62252278f6ab1baf6d8d14eb3f7b1ce9

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=chemist',
  'username' => 'root',
  'password' => 666,
  'name' => 'doctrine',
)),);
