<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/11 05:52:42

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=chemist',
  'username' => 'root',
  'password' => 'mysql',
  'name' => 'doctrine',
)),);
