<?php
// auto-generated by sfSecurityConfigHandler
<<<<<<< HEAD
// date: 2012/02/12 12:47:46
=======
// date: 2012/02/12 17:19:17
>>>>>>> b4f031de62252278f6ab1baf6d8d14eb3f7b1ce9
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
);
