generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Products
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          products
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
        _save_and_add:
          label: Сохранить и добавить
        _save:
          label: Сохранить
        _edit:
          label: Редактировать
        _list:
          label: Назад к списку
        _delete:
          label: Удалить
        _new:
          label: Добавить
      fields:  ~
      list:    ~
      filter:
        display: [purchase_name, preparation_form_id, code, type, action_substance, producer_id]
      form:    ~
      edit:    ~
      new:
        title: Добавить препарат
