# Реестр товаров

Products:
  actAs:
    Timestampable: ~
  columns:
    purchase_name: 
      type: string(255)
    preparation_form_id: 
        type: integer
        notnull: true
    
  relations:
    PreparationForm:
      onDelete: CASCADE
      local: preparation_form_id
      foreign: id
      foreignAlias: PreparationForm  

# Лекарственная форма

PreparationForm:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
      unique: true
      
options:
    collate: utf8_general_ci
    charset: utf8
