# Реестр товаров

Products:
  actAs:
    Timestampable: ~
  columns:
    purchase_name: 
      type: string(255)
      unique: true
    approach_usage:
      type: string
    type: 
      type: string(255)
    code: 
      type: string(255)
    action_substance:
      type: string(255)
    available: 
      type: integer
    preparation_form_id: 
      type: integer
      notnull: true  
    producer_id:
      type: integer
      
  relations:
    PreparationForm:
      onDelete: CASCADE
      local: preparation_form_id
      foreign: id
      foreignAlias: PreparationForm  
    Producer:
      onDelete: CASCADE
      local: producer_id
      foreign: id
      foreignAlias: Producer 

# Лекарственная форма

PreparationForm:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
      unique: true
      
# Производители

Producer:
  actAs:
    Timestampable: ~
  columns:
    name:
      type: string(255)
      notnull: true
      unique: true     
      
# Накладные

Reports:
  columns:
    name:
      type: string(255)
      notnull: true
      unique: true  
    among: 
      type: integer
    product_id:
      type: integer

  relations:
    Products:
      onDelete: CASCADE
      onUpdate: CASCADE
      local: product_id
      foreign: id
      foreignAlias: Products
      
options:
    collate: utf8_general_ci
    charset: utf8